# Minimal iperf3 server workload for CVM network benchmarking.

format = 5

[workload]
name = "iperf-benchmark"
version = "v0.1.2"
base-image-mode = "whitelist"
base-image = ["0xaef8fc89416f01494ec6534de68d30aab26d7598db8a05967b0ba7d3ecb259d2/automata-linux:v0.3.0-debug"]
image = { build = ".", containerfile = "Containerfile" }
ports = ["5201:5201"]
restart = "unless-stopped"
