format = 5

[package]
measured-data = ["/data/public.txt", "/data/private.txt"]
unmeasured-data = [
  "/myconfig.env",
  "/runtime/public.env",
  "/runtime/private.env",
  "/second_level/",
]

[workload]
name = "selective-data-smoke"
version = "v0.1.2"
base-image-mode = "whitelist"
base-image = ["automata-linux:v0.2.7-debug"]
image = { build = ".", containerfile = "Containerfile" }
ports = ["3120:3120/tcp"]
restart = "unless-stopped"
measured-data = ["/data/public.txt"]
unmeasured-data = ["/myconfig.env", "/runtime/public.env", "/second_level/"]
unmeasured-env-file = ["/myconfig.env", "/runtime/public.env"]

[workload.environment]
SMOKE_PORT = "3120"

[dependencies.sidecar]
image = { build = ".", containerfile = "Containerfile.sidecar" }
restart = "unless-stopped"
measured-data = ["/data/private.txt"]
unmeasured-data = ["/runtime/private.env"]
unmeasured-env-file = "/runtime/private.env"

[dependencies.sidecar.environment]
SIDECAR_PORT = "3121"
